Post http://localhost:5220/api/todos
content-type: application/json

{
	"Name": "Go To Work",
	"IsComplete": false
}

###

Get http://localhost:5220/api/todos/complete
content-type: application/json


###

Get http://localhost:5220/api/todos
content-type: application/json

###

Put http://localhost:5220/api/todos/1
content-type: application/json

{
    "Name": "Wake Up",
    "IsComplete": true
}

###


Delete http://localhost:5220/api/todos/1
content-type: application/json
