Post http://localhost:5220/todoitems
content-type: application/json

{
	"Name": "Wake Up",
	"IsComplete": false
}


###


Get http://localhost:5220/todoitems
content-type: application/json


###

Put http://localhost:5220/todoitems/1
content-type: application/json

{
    "Name": "Wake Up",
    "IsComplete": false
}

###


Delete http://localhost:5220/todoitems/1
content-type: application/json
